version: "3.8"
services:
  orchestrator:
    build: .
    container_name: gpt-orchestrator
    env_file:
      - config/.env
    restart: unless-stopped

  dashboard:
    build: .
    container_name: gpt-dashboard
    command: uvicorn dashboard.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - config/.env
    restart: unless-stopped

