orchestrator:
  interval: 60

risk_manager:
  max_drawdown_pct: 0.05
  daily_loss_limit: 0.02

exchanges:
  binance:
    api_key: ${BINANCE_API_KEY}
    secret: ${BINANCE_SECRET}
  kucoin:
    api_key: ${KUCOIN_API_KEY}
    secret: ${KUCOIN_SECRET}

strategies:
  spot_hft:
    symbol: BTC/USDT
    spread_threshold: 1e-7

  grid:
    symbol: BTC/USDT
    levels: [-0.01, 0.01]
    qty_pct: 0.01

  auto_invest:
    symbols: ["BTC/USDT", "ETH/USDT"]
    qty_pct: 0.005

  tri_arb:
    pairs: ["BTC/USDT", "ETH/USDT", "ETH/BTC"]
    usdt_pct: 0.01
    min_profit: 0.01
    commission: 0.001

  delta_neutral:
    window: 60
    hedge_ratio: 0.5
    asset1: BTC/USDT
    asset2: ETH/USDT

  ai_signals:
    prompt_template: |
      Given the market snapshot:
      {snapshot}
      Generate up to 3 trading signals as JSON list.
    model: gpt-4

  rl_trader:
    model_path: rl_trader
