   - name: Install dependencies
     run: pip install -r requirements.txt

   - name: Install package
     run: pip install -e .

   - name: Lint
     run: flake8 ...

   - name: Run tests
     run: pytest tests/
