name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Встановити Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Встановити залежності
        run: pip install -r requirements.txt

      - name: Перевірка стилю
        run: flake8 . --max-line-length=120 --ignore=E221,E231,E302,E305,W391

      - name: Запуск усіх тестів
        run: pytest

      - name: Тести backtesting
        shell: pwsh
        run: |
          if (Test-Path 'backtesting') {
            pytest backtesting/
          } else {
            Write-Host "⏭ backtesting/ відсутня, пропускаємо"
          }

      - name: Тести paper_trading
        shell: pwsh
        run: |
          if (Test-Path 'paper_trading') {
            pytest paper_trading/
          } else {
            Write-Host "⏭ paper_trading/ відсутня, пропускаємо"
          }
