name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: flake8 .

      - name: Run all tests
        run: |
          pytest || exit 0

      - name: Backtesting tests
        run: |
          if [ -d backtesting ]; then
            pytest backtesting/
          else
            echo "⏭ no backtesting/ directory, skipping"
          fi

      - name: Paper-trading tests
        run: |
          if [ -d paper_trading ]; then
            pytest paper_trading/
          else
            echo "⏭ no paper_trading/ directory, skipping"
          fi
