name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8 .
      - name: Run tests
        run: pytest
      - name: Backtesting tests
        run: pytest backtesting/
      - name: Paper-trading tests
        run: pytest paper_trading/
