name: CI smoke-test

on:
  push:
    branches: [main]

jobs:
  smoke-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install OpenAI client
        run: pip install openai

      - name: OpenAI smoke test (cross-shell)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        # для будь-якої shell:
        run: |
          python -c "import os; key=os.getenv('OPENAI_API_KEY'); print('Key length:', len(key) if key else 'MISSING')"


