name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install flake8 mypy pytest

      - name: Lint & type-check
        run: |
          flake8 .
          mypy .

      - name: Run tests & backtests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: docker build -t yourdockerhubuser/gpt-trading-bot:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push yourdockerhubuser/gpt-trading-bot:latest

      - name: Deploy to local
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: localhost
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            docker compose pull
            docker compose up -d --remove-orphans
